### ISSUE TITLE
Colors on dark mode are really bad

### ISSUE THREAD

**Issue by Kukulkano** [zacky48/check-before-sending-email#1]
Hi. I like this Add-On very much. Thanks for that!

Unfortunately, on my work system it looks horrible. I know it is maybe because of the "Drak Reader" Add-On I use, but I really ned that. Usually, I run a dark theme on my Linux desktop (openSuse with KDE) and also use the "Dark Reader" Add-On in Thunderbird. Now, the Add-On looks like this:

[Image on Imgur](https://i.imgur.com/l0HJGFI.png)

Maybe you can fix colors for being usable on dark mode with "Dark Reader", too?

**Comment by zacky48** [comment]
Kukulkano Thanks for the report.

I checked the add-on display in the following environments and could not reproduce the reported symptoms.

openSUSE Leap 15.6
- KDE Plasma 5.27.11 (Breeza Dark)
THunderbird 128.3.1esr
- Dark Reader 

Are there any other possible causes?

**Comment by Kukulkano** [comment]
Hi and thanks for your answer. I run OpenSUSE LEAP 15.5 with KDE Desktop (Breeze Dark, Style "QtCurve") and currently Thunderbird 128.3.1esr with DarkReader Add-On 4.9.68. But the issue stays if DarkReader is deactivated, so it is not the reason.

Sadly, I'm not able to debug the check-before-sending-email Add-On, as the inspector does not get it (it always deactivates the compose window and shows an empty body for your Add-On). I'm not a pro in TB development, so I cannot investigate further.

I did a quick look into your code and it looks like the worst looking elements are the ones you do not set explicitly both foreground and background colors (like div#title-banner). So some colors are defined by the Thunderbird defaults and this leads to missing contrast on my system?

But I'm not sure. Anyway, if it does not affect others, maybe it is just my system?

**Comment by zacky48** [comment]
Thanks for the detailed situation and the advice!

Although it may not solve the problem, I have explicitly specified the background and text colors for the confirmation screen.
Could you try version 0.2.3

**Comment by Kukulkano** [comment]
Hi. Yes, this is much better now!

[Image on Imgur](https://i.imgur.com/Ya4r3sV.png)

By the way, this dialog is really huge. Maybe you can make the fonts for the domain and adresses somehow smaller? Maybe the same size than the other text? Maybe you can compress the dialog a bit more in general, with less space everywhere all around. It nearly takes my full screen (I run 1920x1200 Pixel monitors on default 100% scaling).

**Comment by zacky48** [comment]
Thank you for your confirmation. I am glad to hear that it has improved.

We will look into adjusting the dialog and font size.
