### ISSUE TITLE
Feature-Request: Allow to chose which tests to do / recipient whitelist

### ISSUE THREAD

**Issue by Kukulkano** [zacky48/check-before-sending-email#2]
Hi. I would suggest the following features as settings for the Add-On:

[x] Ask for sender account
[x] Ask for subject
[x] Ask for body
[x] Ask for recipients

If, for example, subject and body are not selected in the settings, the dialog does not ask to confirm subject and body. For example, I only want to confirm sender and recipients. I would not select subject and body to check.

If nothing was selected, the Add-On acts like it was disabled.

Also, maybe add a whitelist for recipient domains. For example, I like to enter my company domain so I do not get asked to confirm recipients from my company. So I only have to confirm external recipients.

Background: To be honest, I only want to protect me from errors sent to customers. I would not even pop up in case the recipients are all from my company domain. So the whitelist would be a huge helper for me. Also, the body and subject are mostly not an issue for me. I'm mainly interested in recipients confirmation.

**Comment by zacky48** [comment]
Thank you for the feature suggestion!
We have supported it in version 0.3.0

**Comment by Kukulkano** [comment]
Thanks! Will test it next week!
