### ISSUE TITLE
Support for address lists

### ISSUE THREAD

**Issue by AWtnb** [zacky48/check-before-sending-email#3]
Thanks for the great add-on. It is very helpful to have a last check before sending!

I found a bug(maybe).

### Summary

When I try to send to an address list, the check box does not appear and I cannot send.

### Details

When I specify an address list, the checkboxes are not displayed and I cannot fill all the checkboxes, so I cannot send the message.
Now I work around this by right-clicking and expanding the address list.

### Environment

- Thunderbird 128.4.1esr
- Windows 11 Pro 23H2

---

（日本語でもよろしいですか？）

素晴らしいアドオンをありがとうございます。送信前に最後の確認をできてとても助かります！
バグ（？）を発見したので報告です。

### 概要

アドレスリストに対して送信しようとするとチェックボックスが表示されずに送信することができなくなる。

### 詳細

アドレスリストを指定するとチェックボックスが表示されなくなり、全部のチェックを埋めることができないので送信することもできなくなります。
今は右クリックしてアドレスリストを展開することでこの現象を回避しています。

### 環境

- Thunderbird 128.4.1esr
- Windows 11 Pro 23H2

**Comment by zacky48** [comment]
@AWtnb さん　（日本語で大丈夫です！）

ご報告ありがとうございます。
アドレスリストに対して送信しようとするとチェックボックスが表示されずに送信することができなくなるバグの件、
バージョン0.2.4で修正いたしました。

**Comment by AWtnb** [comment]
迅速に対応いただきありがとうございます！

手元の環境でも完璧に動作しました。最高です 🤩

**Comment by zacky48** [comment]
早速のご確認ありがとうございました！
